#!/bin/sh
# Host tests for the runtime: the copy of stdout/stderr into its log, Horizon
# file access (rights, descriptor modes, open-file path matching) and the
# analog-stick mouse cursor.
set -eu
root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
build="$(mktemp -d "${TMPDIR:-/tmp}/wine-nx-console.XXXXXX")"
trap 'rm -rf "$build"' EXIT HUP INT TERM
flags="-std=gnu11 -Wall -Wextra -Werror -fsanitize=address,undefined -fno-omit-frame-pointer"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/std_stream_lines.c" -o "$build/std_stream_lines"
"$build/std_stream_lines"
"${CC:-clang}" $flags -I"$root/include" "$root/wine-nx-probe/tests/horizon_file_access.c" -o "$build/file_access"
"$build/file_access"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/pointer_cursor.c" -o "$build/pointer_cursor"
"$build/pointer_cursor"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_message_queue.c" -o "$build/message_queue"
"$build/message_queue"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_win_timers.c" -o "$build/win_timers"
"$build/win_timers"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_msg_queue.c" -o "$build/msg_queue"
"$build/msg_queue"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_clipboard.c" -o "$build/clipboard"
"$build/clipboard"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/launcher_list.c" -o "$build/launcher_list"
"$build/launcher_list"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/launcher_settings.c" -o "$build/launcher_settings"
"$build/launcher_settings"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/launcher_pe.c" -o "$build/launcher_pe"
"$build/launcher_pe" "$root/wine-nx-probe/build-switch-wow64-dynarec/switch/wine/drive_c"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/sd_read_cache.c" -o "$build/sd_read_cache"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/sd_read_cache_upstream.c" -o "$build/sd_read_cache_upstream"
"$build/sd_read_cache_upstream"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/sd_write_buffer.c" -o "$build/sd_write_buffer"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/sd_stat_cache.c" -o "$build/sd_stat_cache"
"$build/sd_stat_cache"
"$build/sd_write_buffer"
"$build/sd_read_cache"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/sd_cache_policy.c" "$root/wine-nx-probe/source/sd_cache.c" -o "$build/sd_cache_policy"
"$build/sd_cache_policy" '-' 1
"$build/sd_cache_policy" '{"sd-stat-cache":true,"sd-clean-writer-cache":true}' 1
"$build/sd_cache_policy" '{"sd-cn-strategy":false}' 0
"$build/sd_cache_policy" '{"sd-cn-strategy":true}' 1
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/upstream_feature_defaults.c" -o "$build/upstream_feature_defaults"
"$build/upstream_feature_defaults"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/box64_code_arena.c" -o "$build/box64_code_arena"
"$build/box64_code_arena"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_registry.c" -o "$build/registry"
"$build/registry"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/registry_paths.c" -o "$build/registry_paths"
"$build/registry_paths"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_read_redirect.c" -o "$build/read_redirect"
"$build/read_redirect"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_object_dirs.c" -o "$build/object_dirs"
"$build/object_dirs"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_keyboard.c" -o "$build/keyboard"
"$build/keyboard"
"${CC:-clang}" $flags -D__WINESRC__ -DWINE_UNIX_LIB -D_WIN64 -I"$root/include" "$root/wine-nx-probe/tests/horizon_completion.c" -o "$build/completion"
"$build/completion"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_free_range.c" -o "$build/free_range"
"$build/free_range"
python3 "$root/wine-nx-probe/tests/check_horizon_va_search.py"
python3 "$root/wine-nx-probe/tests/check_horizon_guest_reserve.py"
python3 "$root/wine-nx-probe/tests/check_horizon_reservation_transition.py"
python3 "$root/wine-nx-probe/tests/check_horizon_reservation_bounds.py"
python3 "$root/wine-nx-probe/tests/check_commit_chunks.py"
python3 "$root/wine-nx-probe/tests/check_waitable_timer.py"
"${CC:-clang}" $flags -D__WINESRC__ -DWINE_UNIX_LIB -D_WIN64 \
    -I"$root/wine-nx-probe/tests/xinput-shims" -I"$root/include" \
    "$root/wine-nx-probe/tests/xinput_nx_pad.c" -o "$build/xinput_pad"
"$build/xinput_pad"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/thread_profile.c" -o "$build/thread_profile"
"$build/thread_profile"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/box64_options.c" -o "$build/box64_options"
"$build/box64_options"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_pool.c" -o "$build/horizon_pool"
python3 "$root/wine-nx-probe/tests/check_horizon_backings.py"
"$build/horizon_pool"
python3 "$root/wine-nx-probe/tests/check_horizon_backings.py"
"${CC:-clang}" $flags -pthread "$root/wine-nx-probe/tests/horizon_memfile.c" -o "$build/horizon_memfile"
"$build/horizon_memfile"
python3 "$root/wine-nx-probe/tests/check_horizon_sections.py"
python3 "$root/wine-nx-probe/tests/check_horizon_image_info.py"
python3 "$root/wine-nx-probe/tests/check_memory_status.py"
python3 "$root/wine-nx-probe/tests/check_user_profile.py"
python3 "$root/wine-nx-probe/tests/check_sims2_setup.py"
python3 "$root/wine-nx-probe/tests/check_sims2_layout.py"
python3 "$root/wine-nx-probe/tests/check_horizon_sock_bind.py"
python3 "$root/wine-nx-probe/tests/check_dxvk_payload.py"
python3 "$root/wine-nx-probe/tests/check_package_amd64.py"
if [ -f "$root/wine-nx-probe/vendor/dxvk/src/dxvk/dxvk_device_info.cpp" ]; then
    python3 "$root/wine-nx-probe/tests/check_dxvk_requirements.py"
fi
python3 "$root/wine-nx-probe/tools/make-7zr-tree.py" "$build/drive_c" >/dev/null
