/* Simplified Chinese text for Autorun's own launcher. Keep the English keys sorted by strcmp. */
#ifndef WINE_NX_LAUNCHER_ZH_CN_H
#define WINE_NX_LAUNCHER_ZH_CN_H

struct launcher_translation { const char *english, *chinese; };
static const struct launcher_translation launcher_zh_cn[] =
{
    { " (app DLL first)", "（优先使用游戏目录中的 DLL）" },
    { " (download required)", "（需要下载）" },
    { " (gone)", "（已失效）" },
    { "0 - Automatic", "0 - 自动" },
    { "0 - Fast", "0 - 快速" },
    { "0 - Full", "0 - 完整" },
    { "0 - Ignore", "0 - 忽略" },
    { "0 - Off", "0 - 关闭" },
    { "0 - Precise", "0 - 精确" },
    { "0 - Safe", "0 - 安全" },
    { "0 - Small", "0 - 小型" },
    { "1 - Balanced", "1 - 平衡" },
    { "1 - Basic", "1 - 基础" },
    { "1 - Double", "1 - 双精度" },
    { "1 - Fast", "1 - 快速" },
    { "1 - Faster", "1 - 更快" },
    { "1 - Files", "1 - 文件" },
    { "1 - Large", "1 - 大型" },
    { "1 - On", "1 - 开启" },
    { "1 - Reduced", "1 - 精简" },
    { "1 - Weak", "1 - 弱" },
    { "1 - Yield", "1 - 让出时间片" },
    { "1 volume", "1 个磁盘" },
    { "2 - All", "2 - 全部" },
    { "2 - Balanced", "2 - 平衡" },
    { "2 - Guarded", "2 - 保护模式" },
    { "2 - Honor control", "2 - 遵循控制字" },
    { "2 - Hybrid", "2 - 混合" },
    { "2 - Minimal", "2 - 最小" },
    { "2 - SIMD", "2 - SIMD" },
    { "2 - Safe", "2 - 安全" },
    { "2 - WFI", "2 - WFI" },
    { "2 - Weakest", "2 - 最弱" },
    { "3 - Strong", "3 - 强" },
    { "3 - WFE", "3 - WFE" },
    { "3 - Wine", "3 - Wine 优化" },
    { "32-bit", "32 位" },
    { "32-bit forwarder", "32 位转发器" },
    { "32-bit forwarder needed", "需要 32 位转发器" },
    { "4 - TSO", "4 - TSO" },
    { "A and B are the mouse buttons until they are given a key of their own.", "未单独指定按键时，A 和 B 分别作为鼠标左右键。" },
    { "Add", "添加" },
    { "Add Game", "添加游戏" },
    { "Add game", "添加游戏" },
    { "Add to the library", "加入游戏库" },
    { "Added to favorites", "已加入收藏" },
    { "Added to the library", "已加入游戏库" },
    { "Address space", "地址空间" },
    { "Adds barriers to approximate x86 memory ordering. Raise this when a multithreaded game hangs or behaves incorrectly.", "增加内存屏障以模拟 x86 内存顺序。多线程游戏卡住或行为异常时可调高。" },
    { "Advanced flags", "高级选项" },
    { "Aligned-only atomics reduce generated code, but a misaligned LOCK operation will crash.", "仅对齐原子操作可减少生成代码，但未对齐的 LOCK 操作会使程序崩溃。" },
    { "All titles", "全部游戏" },
    { "Any", "任意" },
    { "Apostrophe", "撇号" },
    { "Arguments", "启动参数" },
    { "Arguments removed", "已移除启动参数" },
    { "Arguments saved", "已保存启动参数" },
    { "Arrow keys", "方向键" },
    { "Artwork", "封面图片" },
    { "Artwork download failed", "封面下载失败" },
    { "Artwork downloaded", "封面下载完成" },
    { "Atmosphere did not say which this console is on.", "无法从 Atmosphère 判断当前是否使用 emuMMC。" },
    { "Autorun 32-bit", "Autorun 32 位" },
    { "Autorun cannot run this executable.", "Autorun 无法运行该程序文件。" },
    { "Autorun itself on the home menu with the 39-bit address space required by AMD64 programs. Only on an emuMMC.", "在 HOME 菜单创建 Autorun 转发器，提供 AMD64 程序所需的 39 位地址空间。仅应在 emuMMC 使用。" },
    { "Autorun starts itself again instead of closing to the HOME menu. A forwarder made by sphaira cannot do it and stops the console.", "程序结束后重新打开 Autorun，而非返回 HOME 菜单。sphaira 创建的转发器不支持此功能，可能导致主机停止响应。" },
    { "Autorun update", "Autorun 更新" },
    { "Autorun updates", "Autorun 更新" },
    { "Autorun's", "Autorun 默认" },
    { "Autorun's controls, or this program's own over them. Turning them off keeps the keys that were set, for when they are wanted again.", "可使用 Autorun 默认按键，或由此程序的专用按键覆盖。关闭专用按键不会删除已设置的按键。" },
    { "Back", "返回" },
    { "Backing up launcher", "正在备份启动器" },
    { "Backing up runtime", "正在备份运行环境" },
    { "Backslash", "反斜杠" },
    { "Backspace", "退格键" },
    { "Backtick", "反引号" },
    { "Box64 options", "Box64 选项" },
    { "C: and Z:", "C: 与 Z:" },
    { "Cached", "已缓存" },
    { "Cancel", "取消" },
    { "Cannot run here", "无法从这里运行" },
    { "Caps lock", "大写锁定" },
    { "Change", "更改" },
    { "Change the search or favorite filter, or show hidden games in Settings.", "调整搜索或收藏筛选条件，也可在设置中显示隐藏游戏。" },
    { "Check for update", "检查更新" },
    { "Checking CNB releases", "正在检查 CNB 发布版本" },
    { "Checking for updates", "正在检查更新" },
    { "Choose", "选择" },
    { "Choose SteamGridDB game", "选择 SteamGridDB 游戏" },
    { "Choose a volume", "选择磁盘" },
    { "Choose an official DXVK GitHub release.", "选择 GitHub 上的 DXVK 官方发布版本。" },
    { "Choose an official VKD3D GitHub release.", "选择 GitHub 上的 VKD3D 官方发布版本。" },
    { "Choose storage", "选择存储设备" },
    { "Choose the game's executable at its new location.", "选择游戏程序文件的新位置。" },
    { "Close", "关闭" },
    { "Close Autorun and go back to the Homebrew Menu?", "关闭 Autorun 并返回自制程序菜单？" },
    { "Close and reopen Autorun to use the new version.", "关闭并重新打开 Autorun 即可使用新版本。" },
    { "Comma", "逗号" },
    { "Compact", "简洁" },
    { "Compatibility and lower-level DynaRec controls supported by Wine-NX's embedded Box64 backend.", "内置 Box64 后端支持的兼容性及底层动态重编译选项。" },
    { "Compositor", "合成器" },
    { "Configured", "已配置" },
    { "Control", "Ctrl 键" },
    { "Controls", "按键设置" },
    { "Controls floating-point rounding accuracy. Level 1 is fastest; level 0 is most precise.", "控制浮点舍入精度。级别 1 最快，级别 0 最精确。" },
    { "Controls when x87 values use double precision instead of the faster float path.", "控制 x87 数值何时使用双精度，而不是更快的单精度路径。" },
    { "Controls x86 flag handling around calls and returns. Lower values are faster; higher values cover more edge cases.", "控制调用和返回时的 x86 标志位处理。数值越低速度越快，越高则覆盖更多特殊情况。" },
    { "Copy Lossless.dll to sdmc:/switch/wine/lsfg/Lossless.dll.", "将 Lossless.dll 复制到 sdmc:/switch/wine/lsfg/Lossless.dll。" },
    { "Could not connect to GitHub.", "无法连接 GitHub。" },
    { "Could not connect to SteamGridDB.", "无法连接 SteamGridDB。" },
    { "Could not download the update from CNB.", "无法从 CNB 下载更新。" },
    { "Could not install", "安装失败" },
    { "Could not open it", "打开失败" },
    { "Could not save the game library", "无法保存游戏库" },
    { "Could not save the program's settings", "无法保存程序设置" },
    { "Could not start the update worker.", "无法启动更新任务。" },
    { "Could not write run-next.txt", "无法写入 run-next.txt" },
    { "Couldn't update Autorun", "Autorun 更新失败" },
    { "Cover downloaded.", "封面下载完成。" },
    { "Credits", "鸣谢" },
    { "Current", "当前" },
    { "Custom file", "自定义文件" },
    { "D-pad", "十字键" },
    { "D-pad down", "十字键下" },
    { "D-pad left", "十字键左" },
    { "D-pad right", "十字键右" },
    { "D-pad up", "十字键上" },
    { "DXVK + VKD3D", "DXVK + VKD3D" },
    { "DXVK HUD", "DXVK 信息层" },
    { "DXVK version", "DXVK 版本" },
    { "Default", "默认" },
    { "Defers x86 flag calculation until the flags are needed.", "延迟计算 x86 标志位，直到实际需要时再计算。" },
    { "Delete", "删除键" },
    { "Diagnostics", "诊断" },
    { "Direct3D renderer", "Direct3D 渲染器" },
    { "Disabled", "关闭" },
    { "Do not offer another forwarder", "不使用其他转发器" },
    { "Done", "完成" },
    { "Down arrow", "下方向键" },
    { "Download", "下载" },
    { "Download artwork", "下载封面" },
    { "Download the highest-rated square, portrait and hero artwork for this match.", "下载该游戏评分最高的方形、竖版和横幅图片。" },
    { "Downloading artwork", "正在下载封面" },
    { "Downloading from GitHub...", "正在从 GitHub 下载…" },
    { "Downloading update", "正在下载更新" },
    { "Edit controls", "编辑按键" },
    { "Enabled", "开启" },
    { "End", "End 键" },
    { "Enter", "回车键" },
    { "Equals", "等号" },
    { "Escape", "Esc 键" },
    { "Executable location updated", "已更新程序路径" },
    { "Exit", "退出" },
    { "Exit Autorun", "退出 Autorun" },
    { "FPS", "帧率" },
    { "FPS shows only the frame rate. Compact shows the DirectX version, FPS and frame times. Full also shows the DXVK version, GPU, video memory and shader compiler activity. The DXVK HUD does not cover VKD3D's D3D12 rendering.", "帧率模式仅显示帧率；简洁模式增加 DirectX 版本和帧时间；完整模式还显示 DXVK 版本、GPU、显存和着色器编译信息。DXVK 信息层不覆盖 VKD3D 的 D3D12 渲染。" },
    { "Favorite", "收藏" },
    { "Favorites only", "仅收藏" },
    { "File too large", "文件过大" },
    { "Files", "文件" },
    { "Filter and sort", "筛选与排序" },
    { "Finger down", "手指下滑" },
    { "Finger drag", "手指拖动" },
    { "Finger left", "手指左滑" },
    { "Finger right", "手指右滑" },
    { "Finger up", "手指上滑" },
    { "Folder", "文件夹" },
    { "For games linked for a fixed address in the low 4 GB, which only run with 32 bits. Named above as soon as it is made, and games that need it are sent to it. Only on an emuMMC: an installed entry is what the console reports online.", "为固定使用低 4 GB 地址的游戏创建 32 位转发器。创建后会在上方显示名称，相关游戏会交由它启动。仅应在 emuMMC 使用：主机会向线上服务报告已安装的应用。" },
    { "Frame Generation", "帧生成" },
    { "Frame rate limit", "帧率上限" },
    { "Framebuffer", "帧缓冲" },
    { "Full", "完整" },
    { "Game Settings", "游戏设置" },
    { "Game added to the library", "游戏已加入游戏库" },
    { "Game defaults", "游戏默认设置" },
    { "Game unavailable", "游戏不可用" },
    { "Games you start appear here, the most recent first. Open your library to choose one.", "启动过的游戏会显示在这里，最近游玩的排在前面。请打开游戏库选择游戏。" },
    { "General", "常规" },
    { "Generates one frame between each pair of game frames for Vulkan, DXVK and VKD3D only. Output follows the physical display resolution and uses synchronized presentation regardless of the VSync setting.", "仅为 Vulkan、DXVK 和 VKD3D 在相邻游戏帧之间生成一帧。输出采用屏幕实际分辨率，无论垂直同步设置如何都会同步显示。" },
    { "Generates the x86 divide-by-zero exception. Wine-NX enables this by default for compatibility.", "生成 x86 除零异常。Wine-NX 默认开启，以提高兼容性。" },
    { "CNB returned an invalid Autorun release.", "CNB 返回了无效的 Autorun 发布版本。" },
    { "GitHub returned an invalid release catalog.", "GitHub 返回了无效版本列表。" },
    { "Give a new game DXVK", "新游戏默认使用 DXVK" },
    { "Graphics", "图形" },
    { "Hidden", "已隐藏" },
    { "Hidden from the library", "已从游戏库隐藏" },
    { "Hidden programs stay out of the library unless Settings shows them.", "隐藏的程序不会出现在游戏库中，除非在设置中开启显示。" },
    { "Hide missing programs", "隐藏缺失的程序" },
    { "Hide unavailable games. USB games return when the drive reconnects.", "隐藏文件缺失的游戏。重新连接 USB 磁盘后，游戏会再次显示。" },
    { "Home", "主页" },
    { "Home key", "Home 键" },
    { "Info", "说明" },
    { "Insert", "Insert 键" },
    { "Install", "安装" },
    { "Install & restart", "安装并重启" },
    { "Install Autorun update?", "安装 Autorun 更新？" },
    { "Install forwarder", "安装转发器" },
    { "Install now", "立即安装" },
    { "Install this release and restart? Your games and settings will be kept.\n\nKeep the console powered on during installation.", "安装此版本并重启？游戏和设置会保留。\n\n安装期间请勿关机。" },
    { "Installation failed.", "安装失败。" },
    { "Installed", "已安装" },
    { "Installed applications", "已安装的应用" },
    { "Installing", "正在安装" },
    { "Installing - do not power off", "正在安装，请勿关机" },
    { "Installing x86 and x64 files...", "正在安装 x86 和 x64 文件…" },
    { "Installing...", "正在安装…" },
    { "Its own", "此游戏专用" },
    { "Its own keys", "专用按键" },
    { "Keeps the game in the Favorites filter of the library.", "将游戏加入游戏库的收藏筛选列表。" },
    { "Larger translated blocks can improve speed. Level 0 suits self-modifying or heavily threaded code; level 3 suits many Wine games.", "更大的转译块可能提升速度。级别 0 适合自修改或多线程密集代码；级别 3 适合许多 Wine 游戏。" },
    { "Latest", "最新" },
    { "Launcher settings", "启动器设置" },
    { "Left arrow", "左方向键" },
    { "Left bracket", "左方括号" },
    { "Left mouse button", "鼠标左键" },
    { "Left stick", "左摇杆" },
    { "Left stick down", "左摇杆下" },
    { "Left stick left", "左摇杆左" },
    { "Left stick press", "按下左摇杆" },
    { "Left stick right", "左摇杆右" },
    { "Left stick up", "左摇杆上" },
    { "Lets optimized returns re-enter a translated block. Wine-NX defaults to level 2 because PE mappings are not reported as ELF mappings.", "允许优化后的返回重新进入转译块。Wine-NX 默认级别 2，因为 PE 映射不会按 ELF 映射上报。" },
    { "Library", "游戏库" },
    { "Limits real game frames in Vulkan, DXVK and VKD3D. Off adds no cap. VSync and the game's own limit still apply.", "限制 Vulkan、DXVK 和 VKD3D 的实际游戏帧率。关闭时不额外限帧；垂直同步和游戏自身的限制仍然生效。" },
    { "List", "列表" },
    { "Loading", "正在加载" },
    { "Locate executable", "定位程序文件" },
    { "Looking for programs...", "正在查找程序…" },
    { "Make a 32-bit forwarder", "创建 32 位转发器" },
    { "Make an Autorun forwarder", "创建 Autorun 转发器" },
    { "Maximum gap, in bytes, followed while building a translated block. Larger values can improve performance and increase code size.", "构建转译块时允许跟随的最大间距（字节）。较大的值可能提升性能，也会增加代码体积。" },
    { "Menu", "菜单" },
    { "Minus", "减号键" },
    { "Missing", "文件缺失" },
    { "Motion Resolution", "运动估计分辨率" },
    { "Mouse", "鼠标" },
    { "Move the mouse, or send four keys. A game played with the mouse wants both sticks on it; one played with the keyboard wants the keys it walks with.", "可用来移动鼠标，或发送四个方向键。鼠标操作的游戏通常需要双摇杆；键盘操作的游戏则需要对应的移动按键。" },
    { "Moves the mouse", "移动鼠标" },
    { "Name", "名称" },
    { "New games use the bundled DXVK version until another version is selected.", "新添加的游戏默认使用内置 DXVK，直到为其选择其他版本。" },
    { "New update available", "发现新版本" },
    { "Next", "下一项" },
    { "No folders or programs here", "这里没有文件夹或程序" },
    { "No games match this view", "没有符合条件的游戏" },
    { "No matching square, portrait and hero artwork set was found.", "没有找到匹配的方形、竖版和横幅图片组合。" },
    { "No mounted USB volume was found. Connect a drive, then try again.", "没有找到已挂载的 USB 磁盘。连接磁盘后再试。" },
    { "No Autorun update was found in this release channel.", "当前更新通道中没有找到 Autorun 更新。" },
    { "No official release asset was found.", "没有找到官方发布文件。" },
    { "No release notes were provided.", "此版本没有更新说明。" },
    { "None", "无" },
    { "Not connected", "未连接" },
    { "Not enough free SD card space for the update and recovery files.", "SD 卡空间不足，无法存放更新和恢复文件。" },
    { "Not found", "未找到" },
    { "Not set", "未设置" },
    { "Nothing", "无" },
    { "Nothing played yet", "还没有游玩记录" },
    { "Numpad *", "小键盘 *" },
    { "Numpad +", "小键盘 +" },
    { "Numpad -", "小键盘 -" },
    { "Numpad .", "小键盘 ." },
    { "Numpad /", "小键盘 /" },
    { "Numpad 0", "小键盘 0" },
    { "Numpad 1", "小键盘 1" },
    { "Numpad 2", "小键盘 2" },
    { "Numpad 3", "小键盘 3" },
    { "Numpad 4", "小键盘 4" },
    { "Numpad 5", "小键盘 5" },
    { "Numpad 6", "小键盘 6" },
    { "Numpad 7", "小键盘 7" },
    { "Numpad 8", "小键盘 8" },
    { "Numpad 9", "小键盘 9" },
    { "OK", "确定" },
    { "Off", "关闭" },
    { "Autorun releases, changelog and installation for this build's update channel. Games and settings are preserved.", "查看当前构建更新通道中的 Autorun 版本及更新说明。安装时会保留游戏和设置。" },
    { "On", "开启" },
    { "Open Library", "打开游戏库" },
    { "Opening the 32-bit forwarder...", "正在打开 32 位转发器…" },
    { "Optimizes CALL and RET. Level 2 uses Wine-NX's guarded return path so changed blocks remain safe.", "优化 CALL 和 RET。级别 2 使用 Wine-NX 的受保护返回路径，确保代码块变化时仍可安全执行。" },
    { "Options", "选项" },
    { "Page down", "Page Down 键" },
    { "Page up", "Page Up 键" },
    { "Pause", "暂停键" },
    { "Per-game performance and compatibility flags for the Box64 translator.", "为此游戏设置 Box64 转译器的性能与兼容性选项。" },
    { "Performance Mode", "性能模式" },
    { "Period", "句号" },
    { "Play", "启动" },
    { "Please wait...", "请稍候…" },
    { "Plus", "加号键" },
    { "Pre-release", "预发布版" },
    { "Preparing update", "正在准备更新" },
    { "Press + and choose Add game to browse for a Windows executable.", "按 +，选择“添加游戏”，然后选取 Windows 程序文件。" },
    { "Print screen", "截图键" },
    { "Profiler", "性能分析" },
    { "Programs hidden from a game's own settings are listed again.", "重新显示在游戏设置中隐藏的程序。" },
    { "Quit", "退出" },
    { "Recently added", "最近添加" },
    { "Recently launched", "最近启动" },
    { "Reduces per-block metadata. Higher values save memory but can break signal handling or protected software.", "减少每个代码块的元数据。较高数值可节省内存，但可能影响信号处理或受保护软件。" },
    { "Reduces the cost of memory barriers. Higher values are faster and less conservative.", "降低内存屏障开销。数值越高速度越快，但保守性越低。" },
    { "Refresh", "刷新" },
    { "Refresh releases", "刷新版本列表" },
    { "Remove from the library", "从游戏库移除" },
    { "Removed from favorites", "已取消收藏" },
    { "Removed from the library", "已从游戏库移除" },
    { "Rename", "重命名" },
    { "Resolution used to estimate motion. Lower values reduce GPU work and memory use; generated output still follows the physical display resolution.", "运动估计使用的分辨率。调低可减少 GPU 负载和内存占用；生成画面的输出仍采用屏幕实际分辨率。" },
    { "Restart unavailable", "无法重启" },
    { "Restoring", "正在恢复" },
    { "Restoring previous runtime", "正在恢复旧版运行环境" },
    { "Retry", "重试" },
    { "Return here when a program ends", "程序结束后返回启动器" },
    { "Review Game", "确认游戏" },
    { "Right arrow", "右方向键" },
    { "Right bracket", "右方括号" },
    { "Right mouse button", "鼠标右键" },
    { "Right stick", "右摇杆" },
    { "Right stick down", "右摇杆下" },
    { "Right stick left", "右摇杆左" },
    { "Right stick press", "按下右摇杆" },
    { "Right stick right", "右摇杆右" },
    { "Right stick up", "右摇杆上" },
    { "Running 32-bit address space", "当前使用 32 位地址空间" },
    { "Runs the game.", "启动游戏。" },
    { "SD Card", "SD 卡" },
    { "Same as d-pad", "与十字键相同" },
    { "Samples where every thread spends its time and writes [PROF] lines to wine-nx-runtime.log.", "采样各线程的耗时，并将 [PROF] 信息写入 wine-nx-runtime.log。" },
    { "Search", "搜索" },
    { "Search games", "搜索游戏" },
    { "Searching SteamGridDB...", "正在搜索 SteamGridDB…" },
    { "Sections", "分组" },
    { "Select", "选择" },
    { "Selects how x86 PAUSE behaves in spin loops. The best mode depends on the game's threading.", "选择 x86 PAUSE 在自旋循环中的行为。最佳模式取决于游戏的线程方式。" },
    { "Semicolon", "分号" },
    { "Set", "已设置" },
    { "Settings", "设置" },
    { "Shift", "Shift 键" },
    { "Show hidden programs", "显示隐藏的程序" },
    { "Shown in the library", "已在游戏库显示" },
    { "Slash", "斜杠" },
    { "Sort by", "排序方式" },
    { "Space", "空格键" },
    { "Square, portrait and hero from SteamGridDB...", "正在从 SteamGridDB 下载方形、竖版和横幅图片…" },
    { "Start", "启动" },
    { "Start Autorun through its forwarder or the Homebrew Menu to install an update.", "请通过 Autorun 转发器或自制程序菜单启动后再安装更新。" },
    { "SteamGridDB API key", "SteamGridDB API 密钥" },
    { "SteamGridDB API key (blank removes)", "SteamGridDB API 密钥（留空则移除）" },
    { "SteamGridDB failed.", "SteamGridDB 操作失败。" },
    { "SteamGridDB returned an invalid image.", "SteamGridDB 返回了无效图片。" },
    { "Synchronizes Vulkan, DXVK and VKD3D presentation to the display. LSFG-VK always uses synchronized presentation.", "让 Vulkan、DXVK 和 VKD3D 的画面显示与屏幕同步。LSFG-VK 始终使用同步显示。" },
    { "System", "系统" },
    { "Tab", "Tab 键" },
    { "Takes the highest-rated square, portrait and hero pictures for this game from SteamGridDB.", "从 SteamGridDB 下载该游戏评分最高的方形、竖版和横幅图片。" },
    { "That executable already belongs to another library entry.", "该程序文件已属于另一个游戏库条目。" },
    { "That file is too large to open here; edit it on a computer.", "文件太大，无法在此打开；请在电脑上编辑。" },
    { "The SD card could not complete the update. The previous runtime was kept.", "SD 卡未能完成更新，旧版运行环境已保留。" },
    { "The SteamGridDB API key is missing or was rejected.", "SteamGridDB API 密钥缺失或被拒绝。" },
    { "The artwork cache directory could not be created.", "无法创建封面缓存目录。" },
    { "The command line after the program's name, kept beside it as NAME.args.txt. Leave it empty to remove them.", "附加在程序名后的命令行参数，保存在旁边的 NAME.args.txt 中。留空可移除参数。" },
    { "The compositor draws every window through OpenGL. The framebuffer copies window pixels straight to the screen, for when the compositor misbehaves.", "合成器通过 OpenGL 绘制窗口；帧缓冲模式直接复制窗口像素，可在合成器异常时使用。" },
    { "The downloaded archive failed SHA-256 verification.", "下载的压缩包未通过 SHA-256 校验。" },
    { "The downloaded archive is invalid.", "下载的压缩包无效。" },
    { "The downloaded cover could not be saved.", "无法保存下载的封面。" },
    { "The executable could not be found. Remove this entry and add the game again at its new location.", "找不到程序文件。请移除此条目，再从新位置添加游戏。" },
    { "The executable is missing or is not supported by this build.", "程序文件缺失，或此版本不支持该程序。" },
    { "The forwarder made with a 32-bit address space, for games that need the low 4 GB. A game that needs it is offered to that forwarder, which the console opens in this one's place and which starts the game by itself.", "使用 32 位地址空间的转发器，供需要低 4 GB 地址的游戏使用。需要它的游戏会交由转发器启动。" },
    { "The framebuffer copies window pixels straight to the screen, for when the OpenGL compositor misbehaves.", "帧缓冲模式直接把窗口像素复制到屏幕，可在 OpenGL 合成器异常时使用。" },
    { "The game library is unreadable. It was preserved and no games were loaded.", "无法读取游戏库。原文件已保留，本次未加载游戏。" },
    { "The keys could not be saved to the card.", "无法将按键设置保存到 SD 卡。" },
    { "The keys every program's controls send, unless the program has its own.", "所有程序默认使用的按键映射；程序专用设置可覆盖它。" },
    { "The keys this program's controls send, over the ones everything else sends.", "编辑此程序覆盖默认设置的按键映射。" },
    { "The library finds programs within two folders of drive_c by itself; others found with the file browser can be added.", "游戏库会自动查找 drive_c 下两层目录内的程序；其他位置的程序可通过文件浏览器添加。" },
    { "The library is full.", "游戏库已满。" },
    { "The name shown in the library. Y goes back to the name in the program's own resources.", "游戏库中显示的名称。按 Y 可恢复为程序资源中的原名称。" },
    { "The options could not be saved.", "无法保存选项。" },
    { "The options file is too large to edit.", "选项文件太大，无法编辑。" },
    { "The projects and platform references used by Autorun.", "Autorun 使用的项目和平台参考资料。" },
    { "The release could not be written to the SD card.", "无法将版本文件写入 SD 卡。" },
    { "The release is damaged or does not contain a compatible Autorun runtime.", "发布包损坏，或不含兼容的 Autorun 运行环境。" },
    { "The saved game library could not be migrated.", "无法迁移已保存的游戏库。" },
    { "The selected release is ready.", "所选版本已准备就绪。" },
    { "The update could not be written to the SD card.", "无法将更新写入 SD 卡。" },
    { "The update failed SHA-256 verification.", "更新未通过 SHA-256 校验。" },
    { "The update is ready.", "更新已准备就绪。" },
    { "The update recovery files could not be cleared.", "无法清理更新恢复文件。" },
    { "The update was cancelled.", "更新已取消。" },
    { "This console is NOT on emuMMC.", "当前主机未使用 emuMMC。" },
    { "This console is on emuMMC.", "当前主机正在使用 emuMMC。" },
    { "This forwarder", "当前转发器" },
    { "This game is already in your library.", "游戏库中已有这个游戏。" },
    { "Title", "标题" },
    { "Turn over", "切换" },
    { "USB", "USB" },
    { "Unavailable", "不可用" },
    { "Up arrow", "上方向键" },
    { "Up one folder", "返回上一级文件夹" },
    { "Up to date", "已是最新" },
    { "Update", "更新" },
    { "Update cancelled. Your runtime was not changed.", "更新已取消，运行环境未改变。" },
    { "Update failed.", "更新失败。" },
    { "Update installed", "更新已安装" },
    { "Update installed.", "更新已安装。" },
    { "Update recovery is required. Restart Autorun before launching a game. If it cannot start, open switch/wine/updates/previous.nro from the Homebrew Menu.", "需要恢复更新。请先重启 Autorun 再启动游戏。如果 Autorun 无法启动，请从自制程序菜单打开 switch/wine/updates/previous.nro。" },
    { "Used to automatically download the community's highest-rated square, portrait and hero artwork.", "用于自动下载社区评分最高的方形、竖版和横幅图片。" },
    { "Uses ARM64 condition flags directly when possible.", "尽可能直接使用 ARM64 条件标志位。" },
    { "Uses LSFG's performance path. Disable it for the quality path, which costs more GPU time.", "使用 LSFG 的性能模式。关闭后采用画质模式，但会占用更多 GPU 时间。" },
    { "Uses faster native NaN behavior instead of precisely reproducing x86 negative NaNs.", "使用更快的原生 NaN 行为，不精确模拟 x86 的负 NaN。" },
    { "VKD3D version", "VKD3D 版本" },
    { "VSync", "垂直同步" },
    { "Verbose traces", "详细日志" },
    { "Verifying download...", "正在校验下载…" },
    { "What the d-pad sends", "与十字键相同" },
    { "What the game needs of the address space Horizon gives Autorun. A game linked for a fixed address in the low 4 GB runs only under a forwarder made with 32 bits; the forwarder decides this, and a game that needs one it was not given is not started.", "游戏对 Horizon 地址空间的要求。固定使用低 4 GB 地址的游戏只能通过 32 位转发器运行；需要该转发器却未使用时，游戏不会启动。" },
    { "What's new", "更新内容" },
    { "Windows shown by", "窗口显示方式" },
    { "Wine is getting ready...", "Wine 正在准备…" },
    { "Wine uses its built-in renderer. DXVK + VKD3D uses Vulkan for Direct3D 9/10/11/12. Graphics DLLs next to the game have priority.", "Wine 使用内置渲染器；DXVK + VKD3D 通过 Vulkan 运行 Direct3D 9/10/11/12。游戏目录中的图形 DLL 优先。" },
    { "Wine's traces go to wine-nx-runtime.log for every program without its own setting.", "没有单独设置的程序会把 Wine 详细日志写入 wine-nx-runtime.log。" },
    { "Writes Wine's traces to wine-nx-runtime.log, which slows the program down. Global follows the setting in Settings (X on the library).", "将 Wine 的详细日志写入 wine-nx-runtime.log，会降低运行速度。全局设置位于游戏库的“设置”(X)。" },
    { "Your library is empty", "游戏库为空" },
    { "[PROF] lines with where each thread spends its time.", "记录各线程耗时的 [PROF] 日志。" },
    { "asking for the console's key", "获取主机密钥" },
    { "building the control", "构建控制内容" },
    { "building the meta", "构建元数据" },
    { "building the program", "构建程序内容" },
    { "listing it on the home menu", "添加到 HOME 菜单" },
    { "opening the content store", "打开内容存储" },
    { "starting", "启动" },
    { "taking away what was there", "移除原有内容" },
    { "updating the database", "更新数据库" },
    { "working", "操作" },
    { "writing the contents", "写入内容" },

};

#endif
