#!/usr/bin/env python3
"""Compile the FSR 1.0 passes of win32u's scaled presentation to SPIR-V.

tools/fshack_easu.comp and tools/fshack_rcas.comp become the two arrays in
dlls/win32u/fshack_fsr_spv.h, which vulkan.c includes: Wine's build does not
run glslangValidator. Run this after changing either shader; --check only says
whether the header is what they compile to.
"""
from pathlib import Path
import subprocess
import sys
import tempfile

root = Path(__file__).resolve().parent.parent
shaders = [('easu_comp_spv', root / 'tools/fshack_easu.comp'), ('rcas_comp_spv', root / 'tools/fshack_rcas.comp')]
header = root / 'dlls/win32u/fshack_fsr_spv.h'


def words(source):
    with tempfile.TemporaryDirectory() as folder:
        out = Path(folder) / 'shader.spv'
        subprocess.run(['glslangValidator', '-V', '--target-env', 'vulkan1.0', '-I' + str(root / 'tools'),
                        '-o', str(out), str(source)], check=True, stdout=subprocess.DEVNULL)
        data = out.read_bytes()
    return [int.from_bytes(data[i:i + 4], 'little') for i in range(0, len(data), 4)]


text = ['/* Generated by tools/make_fshack_shaders.py from tools/fshack_easu.comp and',
        ' * tools/fshack_rcas.comp, which use AMD FidelityFX FSR 1 (tools/fsr1, MIT). */', '']
for name, source in shaders:
    spv = words(source)
    text.append(f'static const uint32_t {name}[] =')
    text.append('{')
    for i in range(0, len(spv), 8):
        text.append('    ' + ', '.join(f'0x{w:08x}' for w in spv[i:i + 8]) + ',')
    text.append('};')
    text.append('')
text = '\n'.join(text)
if '--check' in sys.argv:
    sys.exit(0 if header.exists() and header.read_text() == text else 'dlls/win32u/fshack_fsr_spv.h is out of date')
header.write_text(text)
